<a href="https://colab.research.google.com/github/ChungHanYang/camera-caliberation/blob/master/calibration_assignment_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ASSIGNMENT : CAMERA CALIBRATION

#### A few guidelines:
#### Before going further, read the accompanying document CalibrationAssignment.docx  which describes the assignment and the the things you need to do.
#### Write a separate report answering the questions described in CalibrationAssignment.docx. Upload the report (as a .pdf file) as well as the completed .ipynb file with outputs on Blackboard
Each student should work on the assignment independently.

The code provided can be run on Google Colaboratory -- colab.research.google.com -- with only one modification (see below). 

In [0]:
import numpy as np
import cv2
import scipy.io
import os
from numpy.linalg import norm
from matplotlib import pyplot as plt
from numpy.linalg import det
from numpy.linalg import inv
from scipy.linalg import rq
from scipy.linalg import solve
from scipy.linalg import lstsq
from scipy.linalg import qr
from numpy.linalg import svd
from math import sqrt

####This part of the code lets you use files from your Google Drive account
####You need not use this if you are not using Google Colaboratory
####Running code on Google Colab

(a) Make a folder on Google Drive, upload this file and all the data files provided to you into the same folder

(b) The last part of the URL will serve as the "folder_id" in the line below

If you are unsure, you can read further here : https://stackoverflow.com/questions/48376580/google-colab-how-to-read-data-from-my-google-drive

In [0]:
from google.colab import files
uploaded = files.upload()

Saving pt_corres.mat to pt_corres.mat
Saving rubik_2D_pts.mat to rubik_2D_pts.mat
Saving rubik_3D_pts.mat to rubik_3D_pts.mat


####PART 1: Given corresponding 2d points in the image and 3d coordinates with known extrinsics, estimate the camera intrinsics of the form given in the CalibrationAssignment.docx

In [0]:
# Code for Part 1 starts here

# Step 1: Load the data file pt_corres.mat
data_part1 = scipy.io.loadmat('pt_corres.mat')
cam_pts_3D = data_part1['cam_pts_3D']         # Load the 3d points
pts_2D = data_part1['pts_2D']                 # Load the corresponding 2d points

print pts_2D.shape
print cam_pts_3D.shape

# Step 2: Write your code here to compute the camera intrinsics
height_2D, width_2D = pts_2D.shape
height_3D, width_3D = cam_pts_3D.shape
for i in range(width_3D):
  cam_pts_3D[0][i] /= cam_pts_3D[2][i]
  cam_pts_3D[1][i] /= cam_pts_3D[2][i]
  cam_pts_3D[2][i] /= cam_pts_3D[2][i]
  
# K = solve(cam_pts_3D,pts_2D)
a = np.array([[cam_pts_3D[1][0], 1], [cam_pts_3D[1][1], 1], [cam_pts_3D[1][2], 1], [cam_pts_3D[1][3], 1], [cam_pts_3D[1][4], 1], [cam_pts_3D[1][5], 1], [cam_pts_3D[1][6], 1], 
              [cam_pts_3D[1][7], 1], [cam_pts_3D[1][8], 1], [cam_pts_3D[1][9], 1], [cam_pts_3D[1][10], 1], [cam_pts_3D[1][11], 1], [cam_pts_3D[1][12], 1], [cam_pts_3D[1][13], 1],
              [cam_pts_3D[1][14], 1], [cam_pts_3D[1][15], 1], [cam_pts_3D[1][16], 1], [cam_pts_3D[1][17], 1], [cam_pts_3D[1][18], 1], [cam_pts_3D[1][19], 1], [cam_pts_3D[1][20], 1],
              [cam_pts_3D[1][21], 1], [cam_pts_3D[1][22], 1], [cam_pts_3D[1][23], 1], [cam_pts_3D[1][24], 1], [cam_pts_3D[1][25], 1], [cam_pts_3D[1][26], 1], [cam_pts_3D[1][27], 1],])
b = np.array([pts_2D[1][0], pts_2D[1][1], pts_2D[1][2], pts_2D[1][3], pts_2D[1][4], pts_2D[1][5], pts_2D[1][6], pts_2D[1][7], pts_2D[1][8], pts_2D[1][9], 
              pts_2D[1][10], pts_2D[1][11], pts_2D[1][12], pts_2D[1][13], pts_2D[1][14], pts_2D[1][15], pts_2D[1][16], pts_2D[1][17], pts_2D[1][18], pts_2D[1][19], 
              pts_2D[1][20], pts_2D[1][21], pts_2D[1][22], pts_2D[1][23], pts_2D[1][24], pts_2D[1][25], pts_2D[1][26], pts_2D[1][27]])
y = lstsq(a, b)[0] #(alpha_y, p_y)


c = np.array([[cam_pts_3D[0][0], cam_pts_3D[1][0], 1], [cam_pts_3D[0][1], cam_pts_3D[1][1], 1], [cam_pts_3D[0][2], cam_pts_3D[1][2], 1], [cam_pts_3D[0][3], cam_pts_3D[1][3], 1], [cam_pts_3D[0][4], cam_pts_3D[1][4], 1], 
              [cam_pts_3D[0][5], cam_pts_3D[1][5], 1], [cam_pts_3D[0][6], cam_pts_3D[1][6], 1], [cam_pts_3D[0][7], cam_pts_3D[1][7], 1], [cam_pts_3D[0][8], cam_pts_3D[1][8], 1], [cam_pts_3D[0][9], cam_pts_3D[1][9], 1], 
              [cam_pts_3D[0][10], cam_pts_3D[1][10], 1], [cam_pts_3D[0][11], cam_pts_3D[1][11], 1], [cam_pts_3D[0][12], cam_pts_3D[1][12], 1], [cam_pts_3D[0][13], cam_pts_3D[1][13], 1], [cam_pts_3D[0][14], cam_pts_3D[1][14], 1],
              [cam_pts_3D[0][15], cam_pts_3D[1][15], 1], [cam_pts_3D[0][16], cam_pts_3D[1][16], 1], [cam_pts_3D[0][17], cam_pts_3D[1][17], 1], [cam_pts_3D[0][18], cam_pts_3D[1][18], 1], [cam_pts_3D[0][19], cam_pts_3D[1][19], 1],
              [cam_pts_3D[0][20], cam_pts_3D[1][20], 1], [cam_pts_3D[0][21], cam_pts_3D[1][21], 1], [cam_pts_3D[0][22], cam_pts_3D[1][22], 1], [cam_pts_3D[0][23], cam_pts_3D[1][23], 1], [cam_pts_3D[0][24], cam_pts_3D[1][24], 1],
              [cam_pts_3D[0][25], cam_pts_3D[1][25], 1], [cam_pts_3D[0][26], cam_pts_3D[1][26], 1], [cam_pts_3D[0][27], cam_pts_3D[1][27], 1]])
d = np.array([pts_2D[0][0], pts_2D[0][1], pts_2D[0][2], pts_2D[0][3], pts_2D[0][4], pts_2D[0][5], pts_2D[0][6], pts_2D[0][7], pts_2D[0][8], pts_2D[0][9], pts_2D[0][10], pts_2D[0][11], pts_2D[0][12], 
              pts_2D[0][2], pts_2D[0][13], pts_2D[0][14], pts_2D[0][15], pts_2D[0][16], pts_2D[0][17], pts_2D[0][18], pts_2D[0][19], pts_2D[0][20], pts_2D[0][22], pts_2D[0][23], pts_2D[0][24], pts_2D[0][25], pts_2D[0][26], pts_2D[0][27]])
x = lstsq(c, d)[0] ##(alpha_x, s, p_x)



#K = [x,
    #[0,y],
     #last]
print x
print y


# Code for Part 1 ends here

(2, 28)
(3, 28)
[2175.41552191  312.87665392  864.45654426]
[3428.86005859  627.54555634]


####PART 2: Given 2d points on the image and corresponding 3d points in the world-coordinate system, estimate both intrinsics and extrinsics. You need to fill in the code for the function calibrate() in calib_DLT.ipynb before running the cell below

In [0]:
def calibrate(x,X):
  '''
  This function computes camera projection matrix from 3D scene points
  and corresponding 2D image points with the Direct Linear Transformation (DLT)
  
  '''
  # Your code goes here
  one = np.ones((28,), dtype=int)
  x = np.vstack((x,one)) 
  X = np.vstack((X,one))
  
  array1 = np.array([[0, 0, 0, 0, X[0][0], X[1][0], X[2][0], X[3][0], -x[1][0]*X[0][0], -x[1][0]*X[1][0], -x[1][0]*X[2][0], -x[1][0]*X[3][0]],
                    [X[0][0], X[1][0], X[2][0], X[3][0], 0, 0, 0, 0, -x[0][0]*X[0][0], -x[0][0]*X[1][0], -x[0][0]*X[2][0], -x[0][0]*X[3][0]]
                    ])
  array2 = np.array([[0, 0, 0, 0, X[0][1], X[1][1], X[2][1], X[3][1], -x[1][1]*X[0][1], -x[1][1]*X[1][1], -x[1][1]*X[2][1], -x[1][1]*X[3][1]],
                    [X[0][1], X[1][1], X[2][1], X[3][1], 0, 0, 0, 0, -x[0][1]*X[0][1], -x[0][1]*X[1][1], -x[0][1]*X[2][1], -x[0][1]*X[3][1]]
                    ])
  array3 = np.array([[0, 0, 0, 0, X[0][2], X[1][2], X[2][2], X[3][2], -x[1][2]*X[0][2], -x[1][2]*X[1][2], -x[1][2]*X[2][2], -x[1][2]*X[3][2]],
                    [X[0][2], X[1][2], X[2][2], X[3][2], 0, 0, 0, 0, -x[0][2]*X[0][2], -x[0][2]*X[1][2], -x[0][2]*X[2][2], -x[0][2]*X[3][2]]
                    ])
  array4 = np.array([[0, 0, 0, 0, X[0][3], X[1][3], X[2][3], X[3][3], -x[1][3]*X[0][3], -x[1][3]*X[1][3], -x[1][3]*X[2][3], -x[1][3]*X[3][3]],
                    [X[0][3], X[1][3], X[2][3], X[3][3], 0, 0, 0, 0, -x[0][3]*X[0][3], -x[0][3]*X[1][3], -x[0][3]*X[2][3], -x[0][3]*X[3][3]]
                    ])
  array5 = np.array([[0, 0, 0, 0, X[0][4], X[1][4], X[2][4], X[3][4], -x[1][4]*X[0][4], -x[1][4]*X[1][4], -x[1][4]*X[2][4], -x[1][4]*X[3][4]],
                    [X[0][4], X[1][4], X[2][4], X[3][4], 0, 0, 0, 0, -x[0][4]*X[0][4], -x[0][4]*X[1][4], -x[0][4]*X[2][4], -x[0][4]*X[3][4]]
                    ])
  array6 = np.array([[0, 0, 0, 0, X[0][5], X[1][5], X[2][5], X[3][5], -x[1][5]*X[0][5], -x[1][5]*X[1][5], -x[1][5]*X[2][5], -x[1][5]*X[3][5]],
                    [X[0][5], X[1][5], X[2][5], X[3][5], 0, 0, 0, 0, -x[0][5]*X[0][5], -x[0][5]*X[1][5], -x[0][5]*X[2][5], -x[0][5]*X[3][5]]
                    ])
  array7 = np.array([[0, 0, 0, 0, X[0][6], X[1][6], X[2][6], X[3][6], -x[1][6]*X[0][6], -x[1][6]*X[1][6], -x[1][6]*X[2][6], -x[1][6]*X[3][6]],
                    [X[0][6], X[1][6], X[2][6], X[3][6], 0, 0, 0, 0, -x[0][6]*X[0][6], -x[0][6]*X[1][6], -x[0][6]*X[2][6], -x[0][6]*X[3][6]]
                    ])
  array8 = np.array([[0, 0, 0, 0, X[0][7], X[1][7], X[2][7], X[3][7], -x[1][7]*X[0][7], -x[1][7]*X[1][7], -x[1][7]*X[2][7], -x[1][7]*X[3][7]],
                    [X[0][7], X[1][7], X[2][7], X[3][7], 0, 0, 0, 0, -x[0][7]*X[0][7], -x[0][7]*X[1][7], -x[0][7]*X[2][7], -x[0][7]*X[3][7]]
                    ])
  array9 = np.array([[0, 0, 0, 0, X[0][8], X[1][8], X[2][8], X[3][8], -x[1][8]*X[0][8], -x[1][8]*X[1][8], -x[1][8]*X[2][8], -x[1][8]*X[3][8]],
                    [X[0][8], X[1][8], X[2][8], X[3][8], 0, 0, 0, 0, -x[0][8]*X[0][8], -x[0][8]*X[1][8], -x[0][8]*X[2][8], -x[0][8]*X[3][8]]
                    ])
  array10 = np.array([[0, 0, 0, 0, X[0][9], X[1][9], X[2][9], X[3][9], -x[1][9]*X[0][9], -x[1][9]*X[1][9], -x[1][9]*X[2][9], -x[1][9]*X[3][9]],
                    [X[0][9], X[1][9], X[2][9], X[3][9], 0, 0, 0, 0, -x[0][9]*X[0][9], -x[0][9]*X[1][9], -x[0][9]*X[2][9], -x[0][9]*X[3][9]]
                    ])
  array11 = np.array([[0, 0, 0, 0, X[0][10], X[1][10], X[2][10], X[3][10], -x[1][10]*X[0][10], -x[1][10]*X[1][10], -x[1][10]*X[2][10], -x[1][10]*X[3][10]],
                    [X[0][10], X[1][10], X[2][10], X[3][10], 0, 0, 0, 0, -x[0][10]*X[0][10], -x[0][10]*X[1][10], -x[0][10]*X[2][10], -x[0][10]*X[3][10]]
                    ])
  array12 = np.array([[0, 0, 0, 0, X[0][11], X[1][11], X[2][11], X[3][11], -x[1][11]*X[0][11], -x[1][11]*X[1][11], -x[1][11]*X[2][11], -x[1][11]*X[3][11]],
                    [X[0][11], X[1][11], X[2][11], X[3][11], 0, 0, 0, 0, -x[0][11]*X[0][11], -x[0][11]*X[1][11], -x[0][11]*X[2][11], -x[0][11]*X[3][11]]
                    ])
  array13 = np.array([[0, 0, 0, 0, X[0][12], X[1][12], X[2][12], X[3][12], -x[1][12]*X[0][12], -x[1][12]*X[1][12], -x[1][12]*X[2][12], -x[1][12]*X[3][12]],
                    [X[0][12], X[1][12], X[2][12], X[3][12], 0, 0, 0, 0, -x[0][12]*X[0][12], -x[0][12]*X[1][12], -x[0][12]*X[2][12], -x[0][12]*X[3][12]]
                    ])
  array14 = np.array([[0, 0, 0, 0, X[0][13], X[1][13], X[2][13], X[3][13], -x[1][13]*X[0][13], -x[1][13]*X[1][13], -x[1][13]*X[2][13], -x[1][13]*X[3][13]],
                    [X[0][13], X[1][13], X[2][13], X[3][13], 0, 0, 0, 0, -x[0][11]*X[0][13], -x[0][13]*X[1][13], -x[0][13]*X[2][13], -x[0][13]*X[3][13]]
                    ])
  array15 = np.array([[0, 0, 0, 0, X[0][14], X[1][14], X[2][14], X[3][14], -x[1][14]*X[0][14], -x[1][14]*X[1][14], -x[1][14]*X[2][14], -x[1][14]*X[3][14]],
                    [X[0][14], X[1][14], X[2][14], X[3][14], 0, 0, 0, 0, -x[0][14]*X[0][14], -x[0][14]*X[1][14], -x[0][14]*X[2][14], -x[0][14]*X[3][14]]
                    ])
  array20 = np.array([[0, 0, 0, 0, X[0][19], X[1][19], X[2][19], X[3][19], -x[1][19]*X[0][19], -x[1][19]*X[1][19], -x[1][19]*X[2][19], -x[1][19]*X[3][19]],
                    [X[0][19], X[1][19], X[2][19], X[3][19], 0, 0, 0, 0, -x[0][19]*X[0][19], -x[0][19]*X[1][19], -x[0][11]*X[2][19], -x[0][19]*X[3][19]]
                    ])
  array25 = np.array([[0, 0, 0, 0, X[0][24], X[1][24], X[2][24], X[3][24], -x[1][24]*X[0][24], -x[1][24]*X[1][24], -x[1][24]*X[2][24], -x[1][24]*X[3][24]],
                    [X[0][24], X[1][24], X[2][24], X[3][24], 0, 0, 0, 0, -x[0][24]*X[0][24], -x[0][24]*X[1][24], -x[0][24]*X[2][24], -x[0][24]*X[3][24]]
                    ])
  array26 = np.array([[0, 0, 0, 0, X[0][25], X[1][25], X[2][25], X[3][25], -x[1][25]*X[0][25], -x[1][25]*X[1][25], -x[1][25]*X[2][25], -x[1][25]*X[3][25]],
                    [X[0][25], X[1][25], X[2][25], X[3][25], 0, 0, 0, 0, -x[0][25]*X[0][25], -x[0][25]*X[1][25], -x[0][25]*X[2][25], -x[0][25]*X[3][25]]
                    ])


  A = np.vstack((array1, array2, array3, array4, array5, array6, array7, array8, array9, array10, array11, array12, array13, array14, array15, array20, array25, array26))
  #print A
  U,sigma,VT = svd(A)
  #print sigma

  V = np.transpose(VT)
  
  #print V
  p1 = V[0:4,-1]
  p2 = V[4:8,-1]
  p3 = V[8:12,-1]
  P = np.vstack((p1,p2,p3))

 
  
  return P

#######################################################################################################################################################################################################

def P_to_KRt(P):
  
  M = P[0:3,0:3]
  
  R, Q = rq(M)
    
  K = R/float(R[2,2])
  
  if K[0,0] < 0:
    K[:,0] = -1*K[:,0]
    Q[0,:] = -1*Q[0,:]
    
  if K[1,1] < 0:
    K[:,1] = -1*K[:,1]
    Q[1,:] = -1*Q[1,:]
  
  if det(Q) < 0:
    print 'Warning: Determinant of the supposed rotation matrix is -1'
  
  P_3_3 = np.dot(K,Q)
  
  P_proper_scale = (P_3_3[0,0]*P)/float(P[0,0])
  
  t = np.dot(inv(K), P_proper_scale[:,3])
  
  return K, Q, t

#######################################################################################################################################################################################################


# Step 1 : Load the data files rubik_2D_pts.mat and rubik_3d_pts.mat

pts_3d = scipy.io.loadmat('rubik_3D_pts.mat')['pts_3d'] # 3D points in the world-coordinate system with one of the corners of the Rubik's cube as the origin; side of each smaller cube = 1 unit
pts_2d = scipy.io.loadmat('rubik_2D_pts.mat')['pts_2d'] # The corresponding 2D points on the image rubik_cube.jpg

print pts_2d.shape
print pts_3d.shape


# Step 2: Get the camera calibration matrix P
  
P = calibrate(pts_2d, pts_3d)     

print 'P = ', P 

# Step 3: Use the function P_to_KRt (already written for you) to decompose P into intrinsics (K) and extrinsics (R and t)
[K, R, t] = P_to_KRt(P)

print 'K = ', K
print 'R = ', R
print 't = ', t

# Write code here to compute the average reprojection error (averaged over the 28 points given)
one = np.ones((28,), dtype=int)
pts_3d = np.vstack((pts_3d, one))
project = np.dot(P,pts_3d)
l,w = project.shape
for i in range(28):
  project[0][i] = project[0][i]*(1/project[2][i])
  project[1][i] = project[1][i]*(1/project[2][i])
  project[2][i] = project[2][i]*(1/project[2][i])
err1 = 0
err2 = 0
for i in range(28):
  err1 += (pts_2d[0][i]-project[0][i])**2
for j in range(28):
  err1 += (pts_2d[1][j]-project[1][j])**2

err = sqrt(err1+err2)/28
print pts_2d
print ('-------------------------------------------------------------')
print project
print ('-------------------------------------------------------------')
print err



# Display the given 2D points and the reprojected 2D points on the Rubik's Cube image provided



(2, 28)
(3, 28)
P =  [[ 2.23308102e-01  2.70878169e-02 -4.41655268e-02  6.49183948e-01]
 [ 3.18469634e-03 -1.77119603e-01 -1.43736464e-01  6.88452104e-01]
 [-1.46819264e-06  2.66159014e-05 -5.24103039e-05  1.17459356e-03]]
K =  [[3.81917538e+03 4.37248713e+00 7.83199706e+02]
 [0.00000000e+00 3.79336488e+03 8.14021140e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
R =  [[ 0.99949535  0.02881726 -0.01336482]
 [ 0.01963624 -0.89122052 -0.453145  ]
 [-0.0249694   0.45265389 -0.89133663]]
t =  [-1.20431631 -1.20015036 19.97619144]
[[ 553.17485667  742.29197379  936.02170352 1128.07411957  561.98075348
   749.83988534  938.53767404 1121.36486486  573.72194922  754.87182637
   941.05364455 1121.78419328  582.94717445  759.06511057  942.31162981
  1121.78419328  562.81941032  744.80794431  931.82841933 1115.91359541
   576.65724816  750.25921376  928.89312039 1103.75307125  587.55978706
   754.45249795  926.37714988 1095.36650287]
 [ 583.15683866  586.93079443  593.64004914  598.6719901